
version: '3'

services:
  learnit:
    build: .
    restart: always
    image: learnit
    environment:
      - MONGO_URL=mongodb://mongodb:27017/learnit
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    volumes:
      - .:/app/server
    networks:
      - node-network

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - db_data:/data/db
    networks:
      - node-network

volumes:
  db_data:

networks:
  node-network:
    driver: bridge